### ISSUE TITLE
missing positional argument after upgrade to Python 3.6

### ISSUE THREAD

**Issue by gbowerman** [AtroxDev/haikunator#3]
from haikunator import Haikunator
Haikunator.haikunate()
TypeError: haikunate() missing 1 required positional argument: 'self'

**Comment by Atrox** [comment]
Hey,

you have to first instantiate the class and then call the haikunate method on it.
Like this: `Haikunator().haikunate()`

Thanks,
Atrox

**Comment by gbowerman** [comment]
Thanks, this works:
from haikunator import Haikunator
h = Haikunator()
print(h.haikunate())
